config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts
  resources :users, only: [:new, :create, :edit, :update]

  resources :categories, only: [:new, :create, :show, :edit, :update, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  before_save :generate_slug

	def to_param
		self.slug
	end

  def generate_slug
    str = name.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/,'-'
    str.gsub! /-+/,"-"
    self.slug = str
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_categories
  has_many :categories, through: :post_categories
  belongs_to :user

  mount_uploaders :photos, PhotoUploader

  validates :title, presence: true, uniqueness: true
	validates :body, presence: true

  before_save :generate_slug

	def to_param
		self.slug
	end

  def generate_slug
    str = title.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/,'-'
    str.gsub! /-+/,"-"
    self.slug = str
  end

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  has_secure_password
  mount_uploader :photo, PhotoUploader

  validates :username, presence: true
	validates :printname, presence: true
  validates :password, presence: true

  before_save :generate_slug

	def to_param
		self.slug
	end

  def generate_slug
    str = username.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/,'-'
    str.gsub! /-+/,"-"
    self.slug = str
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] ='Must be logged in to do that'
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_user, except:[:show]
  before_action :set_category, except:[:new, :create]

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category=Category.new(category_params)
    @categories = Category.all

		if @category.save
  		flash['success'] = "New Category created successfully"
  		redirect_to new_category_path
  	else
  		render :new
  	end

  end

  def destroy
    if @category.destroy
      flash['success'] = "Category was deleted successfully"
    end
    redirect_to new_category_path
  end

  def edit
  end

  def update

	 	if @category.update(category_params)
  		flash['success'] = "Category was updated successfully"
  		redirect_to new_category_path
  	else
  		render :edit
  	end
	end

  def set_category
    @category = Category.find_by slug: params[:id]
  end

  private

  def category_params()
    params.require(:category).permit(:name)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_user, except:[:index, :show]
	before_action :set_post, except:[:index, :new, :create]

  def index
		@posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
  		flash['success'] = "Your post was created successfully"
  		redirect_to posts_path
  	else
  		render :new
  	end

  end

  def update
	 	if @post.update(post_params)
  		flash[:success] = "Post was updated successfully"
  		redirect_to post_path(@post)
  	else
  		render :edit
  	end

	end

  def show
		@user = @post.user
	end

	def destroy
		if @post.destroy
			flash[:notice] = "Post was deleted successfully"
  		redirect_to root_path
  	else
  		render :edit
  	end

	end

  def set_post
		@post = Post.find_by slug: params[:id]
	end

  private
    def post_params
			params.require(:post).permit(:title, :tagline, :body, category_ids: [], photos: [])
		end

end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

	def new
	end

	def create

		user = User.where(username: params[:username]).first

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash['success'] = 'Logged in successfully'
			redirect_to root_path
		else
			flash['danger'] = 'There was an error logging in, please try again'
			redirect_to login_path
		end


	end

	def destroy
		session[:user_id] = nil
		flash['success'] = 'Logged out successfully'
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
		@user = User.find_by slug: params[:id]
	end

	def update
		@user = User.find_by slug: params[:id]

	 	if @user.update(user_params)
  		flash['success'] = "User was updated successfully"
  		redirect_to root_path
  	else
  		render :edit
  	end

	end

	private
		def user_params
			params.require(:user).permit(:username, :printname, :password, :photo)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  = render 'shared/errors', object: @category
  .form-horizontal
    .form-group
      =f.label :name, 'Category Name', class: 'control-label col-sm-2'
      .col-sm-2= f.text_field :name, class:'form-control'

  .col-sm-offset-2.col-sm-10= f.submit button, class: 'btn btn-primary'

app/views/categories/edit.html.haml
%h2 Edit Category Name

= render 'form', button: 'Update Category'

app/views/categories/new.html.haml
%h1 All Categories

%ul.list-group
  -@categories.each do |c|
    %li.list-group-item
      %h4= c.name
      .btn-group
      = link_to '<button type="button" class="btn btn-warning"> Edit Category</button>'.html_safe, edit_category_path(c)
      = link_to '<button type="button" class="btn btn-danger"> Delete Category</button>'.html_safe, category_path(c), data: {confirm: "Are you sure -- This can't be undone"}, :method => :delete

= render 'form', button: 'Create New Category'

app/views/layouts/_messages.html.haml
-flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header= link_to "Out With Erin", root_path, :class => 'navbar-brand'

    %ul.nav.navbar-nav
      %li= link_to 'Destinations', '#'
      %li= link_to 'Tips & Tricks', '#'
      %li= link_to 'About Us', '#'
      - if logged_in?
        %li ADMIN CONTROLS ->
        %li= link_to 'New Post', new_post_path
        %li= link_to 'Edit Categories', new_category_path
        %li= link_to 'Edit User Profile', edit_user_path(current_user)
        %li= link_to 'Log Out', logout_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Out With Erin
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    = render 'layouts/navigation'
    #main{role: 'main'}
      .container
        .row
          .span12
            = render 'layouts/messages'
        = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  = render 'shared/errors', object: @post
  .form-horizontal
    .form-group
      = f.label :title, 'Title', class: 'control-label col-sm-2'
      = f.text_field :title, class: 'new_post_title'
    .form-group
      = f.label :tagline, 'Tag Line', class: 'control-label col-sm-2'
      = f.text_field :tagline, class: 'new_post_title'
    .form-group
      = f.label :body, 'Post Body', class: 'control-label col-sm-2'
      = f.text_area :body, class: 'new_post_body'
    .form-group
      = f.label 'Categories', class: 'control-label col-sm-2'
      = f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
        = cb.label( class: 'checkbox inline col-sm-2') {cb.check_box(class: 'checkbox') + cb.text}
    .form-group
      =f.file_field :photos, multiple: true
  = f.submit button, class: 'btn btn-primary'

app/views/posts/edit.html.haml
%h2 Update Post
%br
= render 'form', button: 'Update Post'
%br
= link_to '<button type="button" class="btn btn-danger"> Delete Post</button>'.html_safe, post_path(@post), data: {confirm: 'Are you sure?'}, :method => :delete

app/views/posts/index.html.haml
%h1 TESTING

.container
  - @posts.each do |post|
    %li= link_to post.title, post


-#
-# <div class='container'>
-#
-# 	<% @posts.each_with_index do |post,i| %>
-# 		<% if i==0 || i%3 ==0 %>
-# 			<div class = 'row'>
-# 				<%= render 'post', post:post, i:i%>
-# 		<%elsif (i+1)%3 == 0 %>
-# 			<%= render 'post', post:post, i:i%>
-# 			</div>
-# 			<hr/>
-# 		<%else%>
-# 			<%= render 'post', post:post, i:i %>
-# 		<%end%>
-# 	<% end %>
-#
-# </div>

app/views/posts/new.html.haml
%h1 New Post

%br

= render 'form', button: 'Create Post'

app/views/posts/show.html.haml
.row
  .col-md-9
    .well
      %h1.post-title
      - if logged_in?
        =link_to 'Edit Post', edit_post_path(@post)
      %br
      =@post.title
      %hr
      %p=@post.body
      -@post.photos.each do |p| # for each image
        = image_tag(p.medium.url)
      %br
      - if !@user.nil?
        = image_tag(@user.photo.small.url)

app/views/shared/_errors.html.haml
-if object.errors.any?
  .row
    .alert.alert-danger.span.8{role: 'alert'}
      %h5 Please fix the following errors
      %ul
        -object.errors.full_messages.each do |msg|
          %li= msg

app/views/users/_form.html.haml
= form_for @user do |f|
  = render 'shared/errors', object: @user
  .form-horizontal
    .form-group
      = f.label :username, 'User Name', class: 'control-label col-sm-2'
      .col-sm-2= f.text_field :username, class: 'form-control'
    .form-group
      = f.label :printname, 'Display Name', class: 'control-label col-sm-2'
      .col-sm-2= f.text_field :printname, class: 'form-control'
    .form-group
      = f.label :password, 'Password', class: 'control-label col-sm-2'
      .col-sm-2=  f.password_field :password, class: 'form-control'
    .form-group
      =f.file_field :photo
  .col-sm-offset-2.col-sm-10= f.submit button, class: 'btn btn-primary'

app/views/users/edit.html.haml
%h1 Edit User

= render 'form', button: 'Update User'